name: CI/CD Workflow

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    # Build somente na branch `main`
    - name: Build Angular.js project
      if: github.ref == 'refs/heads/main'
      run: npm run build

    # Cypress Tests para ambas as branches
    - name: Run Cypress tests
      run: npm run cy:run
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}